site_name: Telegram.cr
repo_url: https://github.com/watzon/telegram.cr
edit_uri: https://github.com/watzon/telegram.cr/tree/master/docs/
site_url: https://telegram.shard.ly

theme:
  name: material
  palette:
    - scheme: default
      primary: teal
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.sections
    - navigation.tracking
    - content.code.annotate
  icon:
    logo: fontawesome/brands/telegram
    repo: fontawesome/brands/github
  favicon: images/logo.png

extra_css:
  - stylesheets/extra.css

plugins:
  - search:
      indexing: full
  - mkdocstrings:
      default_handler: crystal
      watch: [src]
  - gen-files:
      scripts:
        - docs/gen_doc_stubs.py
  - literate-nav:
      nav_file: SUMMARY.md
  - section-index
  - macros:
      modules:
        - mkdocstrings.handlers.crystal.macros
      # include_dir: .

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.saneheaders
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.critic
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - deduplicate-toc
  - admonition
  - def_list
  - toc:
      permalink: "#"

# extra:
#   version:
#     method: mike
